Practice2 pull request
andrew-budnitskiy/OI_Practice2 pull request #2
Opened 2021-06-29 13:03 UTC by andrew-budnitskiy

This is pull request for the **second** practice.
Created by Andrew Budnitskiy.
28.06.2021

2021-06-30 12:04 UTC, vasilevkin requested changes

2021-06-30 12:04 UTC, vasilevkin commented on Cats/Cats/ViewController.swift
> +    //В главной таблице 3 ячейки
table should contain all items in the animals list

2021-07-01 11:24 UTC, vasilevkin commented
it looks better now.

Please add SwiftLint to the project and proceed with additional tasks or Practice 3.

2021-07-01 11:57 UTC, andrew-budnitskiy commented on Cats/Cats/AppDelegate.swift
> +//
Issued

2021-07-01 11:57 UTC, andrew-budnitskiy commented on Cats/Cats/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Issued

2021-07-01 11:59 UTC, andrew-budnitskiy commented on Cats/Cats/ViewController.swift
> +    //В главной таблице 3 ячейки
Some transformations were made, and this comment was issued too.

2021-07-01 12:05 UTC, andrew-budnitskiy commented
> it looks better now.
> 
> Please add SwiftLint to the project and proceed with additional tasks or Practice 3.

I'm sorry, but there is'nt additional tasks in this practice - there are in Practice1 or Practice3. Is it necessary add SwiftLint to this practice exactly?

2021-07-01 13:45 UTC, andrew-budnitskiy commented
> it looks better now.
> 
> Please add SwiftLint to the project and proceed with additional tasks or Practice 3.

Issued

2021-07-01 14:00 UTC, vasilevkin commented
proceed with Practice 3.

2021-07-22 20:24 UTC, alekseykorol approved these changes

2021-07-31 18:21 UTC, merged