Practice5 pull request
andrew-budnitskiy/OI_Practice2 pull request #5
Opened 2021-08-12 11:57 UTC by andrew-budnitskiy

This is a pull request for **fifth** practice
Andrew Budnitskiy
12.08.2021

2021-08-12 12:17 UTC, andrew-budnitskiy commented on OI_Practice/OI_Practice/Maps/Map/MapViewController.swift
> +
I have a trouble. It was used MKMarkerAnnotationView for present marker, but click on map marker, created by this annotation's view fires not always quiet as necessary - click on map event fires even when i tap on marker often.
I use MKAnnotationView's subview, created from xib too, but it had no effect.
How can i create a marker with title, click on that doesn't fire click on map?

2021-08-25 13:14 UTC, andrew-budnitskiy commented on OI_Practice/OI_Practice/Maps/Map/MapViewController.swift
> +
fixed

2021-09-08 09:14 UTC, vasilevkin requested changes
this pr should contain changes related to practice 5 only.
please check carefully what files and commits are included.

you can create a new pr instead of this one, if you like

2021-09-08 09:14 UTC, vasilevkin commented on .gitignore
> +# Ignore all other practices
do not add this in gitignore

2021-09-09 09:01 UTC, andrew-budnitskiy commented on .gitignore
> +# Ignore all other practices
fixed

2021-09-09 09:01 UTC, andrew-budnitskiy commented
> this pr should contain changes related to practice 5 only.
> please check carefully what files and commits are included.
> 
> you can create a new pr instead of this one, if you like

fixed

2021-09-09 09:01 UTC, closed without merging